spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://ProductMicroservice
          predicates:
            - Path=/products/**
        - id: user-service
          uri: lb://UserMicroservice
          predicates:
            - Path=/users/**
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  logging:
    level:
      org.springframework: DEBUG
      org.springframework.cloud.gateway: DEBUG