server:
  port: 8888 # Définit le port sur lequel votre config-server sera disponible
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SeifeddineTouj0/SC-ConfigServer
          clone-on-start: true